# apiVersion: v1
# kind: Secret
# metadata:
#   name: healthchecks-secret
#   labels:
#     app: healthchecks
# data:
#   DB_PASSWORD:
#   DB_USER:
#   EMAIL_HOST_PASSWORD:
#   EMAIL_HOST_USER:
#   SECRET_KEY: