apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthchecks-ingress
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:630637833070:certificate/483f7d3f-fc09-46d3-853d-ece8657cc7fc
spec:
  rules:
  - host: hc.fastjobs.sg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      - path: /
        pathType: Prefix
        backend:
          service:
            name: healthchecks-service
            port:
              number: 8000