apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecks-deployment
  labels:
    app: healthchecks
spec:
  selector:
    matchLabels:
      app: healthchecks
  template:
    metadata:
      labels:
        app: healthchecks
    spec:
      containers:
      - name: healthchecks
        image: healthchecks/healthchecks:v2.7
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: 256Mi
            cpu: 50m
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: healthchecks-configmap
        - secretRef:
            name: healthchecks-secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: healthchecks-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: healthchecks-deployment
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70